use_frameworks!

platform :ios, '9.0'

target 'WPDelegates_Example' do
  pod 'WPDelegates', :path => '../'

  target 'WPDelegates_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
